version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_DATABASE: price_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
      TZ: America/Guayaquil
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./prices.sql:/docker-entrypoint-initdb.d/init.sql
    command:
      [
        "--default-authentication-plugin=mysql_native_password",
        "--pid-file=/tmp/mysqld.pid",
        "--tls-version=",
        "--skip-host-cache"
      ]

  web:
    build: .
    container_name: django-app
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: price_db
      DB_USER: user
      DB_PASSWORD: password
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: ["/app/wait-for-mysql.sh", "gunicorn", "core.wsgi:application", "--bind", "0.0.0.0:8000"]

volumes:
  db_data:
